export const FETCH_COURSES_REQUEST = 'FETCH_COURSES_REQUEST';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILED = 'FETCH_COURSES_FAILED';
export const SELECTED_COURSE = 'SELECTED_COURSE';